using DailyDeBugle.Components;
using DailyDeBugle.Data;
using DailyDeBugle.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

var builder = WebApplication.CreateBuilder(args);

AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

// Add services to the container

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

// В Program.cs, после builder.Services.AddRazorComponents()
builder.Services.AddServerSideBlazor()
    .AddHubOptions(options =>
    {
        // Увеличиваем таймауты
        options.ClientTimeoutInterval = TimeSpan.FromSeconds(60);
        options.HandshakeTimeout = TimeSpan.FromSeconds(30);
        options.KeepAliveInterval = TimeSpan.FromSeconds(15);
        options.MaximumReceiveMessageSize = 10 * 1024 * 1024; // 10MB максимум
    });

// Database
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

// Authentication & Authorization
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.Cookie.Name = "auth_token";
        options.LoginPath = "/login";
        options.Cookie.MaxAge = TimeSpan.FromDays(7);
    });
builder.Services.AddAuthorization(DailyDeBugle.Security.AuthorizationPolicyConfiguration.Configure);
builder.Services.AddCascadingAuthenticationState();


// Services
builder.Services.AddScoped<IPublicationService, PublicationService>();
builder.Services.AddScoped<IHeaderFooterService, HeaderFooterService>();
builder.Services.AddScoped<IGlobalTextStyleService, GlobalTextStyleService>();
builder.Services.AddScoped<IIssueService, IssueService>();
builder.Services.AddScoped<ILayoutService, LayoutService>();
builder.Services.AddScoped<IArticleService, ArticleService>();
builder.Services.AddScoped<IUserService, UserService>(); 
builder.Services.AddScoped<ITemplateService, TemplateService>();
builder.Services.AddScoped<IAdvertisementService, AdvertisementService>();

builder.Services.AddLogging();


var app = builder.Build();

// Dev-only: auto-create database/schema if missing.
// The project currently has no EF migrations checked in, so without this the app fails
// when the configured database does not exist yet.
if (app.Environment.IsDevelopment())
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    await db.Database.EnsureCreatedAsync();

    // EnsureCreated doesn't update schema for existing DBs.
    // Since the project doesn't use migrations yet, create new tables if they are missing.
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "ArticleImages" (
            "ArticleImageId" integer GENERATED BY DEFAULT AS IDENTITY,
            "ArticleId" integer NOT NULL,
            "ImagePath" character varying(500) NOT NULL,
            "Caption" character varying(200),
            "SortOrder" integer NOT NULL DEFAULT 0,
            "CreatedAt" timestamp without time zone NOT NULL,
            CONSTRAINT "PK_ArticleImages" PRIMARY KEY ("ArticleImageId"),
            CONSTRAINT "FK_ArticleImages_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Articles" ("ArticleId") ON DELETE CASCADE
        );
        CREATE INDEX IF NOT EXISTS "IX_ArticleImages_ArticleId" ON "ArticleImages" ("ArticleId");
    """);
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
    app.UseHttpsRedirection();
}

app.UseStaticFiles();
app.UseAntiforgery();

app.UseAuthentication();
app.UseAuthorization();

app.MapGet("/api/auth/signin", async (string username, string? returnUrl, IUserService userService, HttpContext httpContext) =>
{
    var users = await userService.GetAllAsync();
    var dbUser = users.FirstOrDefault(u => u.Username == username);
    
    if (dbUser == null) return Results.Redirect("/login?error=InvalidUser");

    var claims = new List<Claim>
    {
        new Claim(ClaimTypes.Name, dbUser.Username),
        new Claim(ClaimTypes.Email, dbUser.Email),
        new Claim(ClaimTypes.Role, dbUser.Role.ToString()),
        new Claim("UserId", dbUser.UserId.ToString())
    };

    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
    var authProperties = new AuthenticationProperties { IsPersistent = true };

    await httpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

    return Results.Redirect(returnUrl ?? "/");
});

app.MapGet("/api/auth/signout", async (HttpContext httpContext) =>
{
    await httpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    return Results.Redirect("/");
});

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.Run();